import { type PropsWithChildren } from "react";
import { Header } from "./Header";
import Head from "next/head";
import { Footer } from "./Footer";

export function Layout({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center">
        {children}
      </main>
      <Footer />
    </>
  );
}
